#1.springboot日志配置
logging:
  #输出级别
  level:
    com.dcqc.demo: info
  #输出路径和文件
  path: D:\\Users\\duochiqingcai\\Documents\\mylog
  file:
    max-size: 10
    max-history: 15
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------

spring:
  #a.数据库连接配置
  datasource: #-->
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/sakila?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    #b.druid连接池配置
    druid:
      initial-size: 5 #初始化连接池大小5
      min-idle: 5 #最小连接数量
      max-active: 20 #最大连接数量
      max-wait: 30000 #获取连接最大等待时间，单位ms
      test-while-idle: true #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      time-between-eviction-runs-millis: 30000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，又作为testWhileIdel执行的依据，单位是ms
      min-evictable-idle-time-millis: 30000 #配置一个连接在池中最小生存的时间，单位是毫秒
      test-on-borrow: false #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      exception-sorter: true #当数据库抛出不可恢复的异常时,抛弃该连接
      max-pool-prepared-statement-per-connection-size: 20 #当值大于0时poolPreparedStatements会自动修改为true
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------

#3.mybatis配置信息
mybatis:
  configuration:
    #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
    map-underscore-to-camel-case: true
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.dcqc.demo.学习笔记.进阶.mybatis.entity
  mapper-locations: classpath:mapper/*.xml