#1.springboot日志配置
logging:
  #输出级别
  level:
    com.dcqc.demo: info
  #输出路径和文件
  path: D:\\Users\\duochiqingcai\\Documents\\mylog
  file:
    max-size: 10
    max-history: 15
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------

spring:
  #a.数据库连接配置
  datasource: #-->
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/management?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------

#3.mybatis配置信息
mybatis:
  configuration:
    #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
    map-underscore-to-camel-case: true
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.dcqc.demo.entity
  mapper-locations: classpath:mapper/*.xml